#!/usr/bin/env bash
# setup.sh — Bootstrap esxi-skill configuration.
#
# Usage:
#   Password is read from stdin (never passed as argument — avoids exposure
#   in process listings).
#
#   ./setup.sh <host> <username> [insecure=1|0] [datacenter] <<<"$PASSWORD"
#
# Example:
#   ./setup.sh 'esxi.lab' 'root' 1 'ha-datacenter' <<<'mypassword'
#
# What it does:
#   1. Install govc if missing (macOS: via brew; Linux: from GitHub releases)
#   2. Write config to ~/.config/esxi-skill/<profile>.env
#   3. Store password in macOS Keychain (service: govc-<host>, account: <user>)
#   4. Test connection with `govc about`

set -euo pipefail

HOST="${1:?Usage: setup.sh <host> <username> [insecure] [datacenter] <<<password}"
USERNAME="${2:?Username required}"
INSECURE="${3:-1}"
DATACENTER="${4:-ha-datacenter}"
PROFILE="${ESXI_PROFILE:-default}"

# Read password from stdin
if [ -t 0 ]; then
  echo "Error: password must be piped via stdin (not typed)." >&2
  echo "Example: ./setup.sh host user <<<'password'" >&2
  exit 2
fi
PASSWORD=$(cat)

if [ -z "$PASSWORD" ]; then
  echo "Error: password is empty." >&2
  exit 2
fi

log() { echo "[setup] $*"; }

# ---------- 1. Install govc if missing ----------
if ! command -v govc >/dev/null 2>&1; then
  log "govc not found, installing..."
  case "$(uname)" in
    Darwin)
      if ! command -v brew >/dev/null 2>&1; then
        echo "Error: Homebrew required to auto-install govc on macOS." >&2
        echo "Install brew or download govc manually from https://github.com/vmware/govmomi/releases" >&2
        exit 3
      fi
      brew install govc
      ;;
    Linux)
      arch=$(uname -m)
      case "$arch" in
        x86_64) arch="x86_64" ;;
        aarch64|arm64) arch="arm64" ;;
        *) echo "Error: unsupported Linux arch: $arch" >&2; exit 3 ;;
      esac
      tmp=$(mktemp -d)
      trap "rm -rf $tmp" EXIT
      url="https://github.com/vmware/govmomi/releases/latest/download/govc_Linux_${arch}.tar.gz"
      log "Downloading $url"
      curl -fsSL "$url" | tar -C "$tmp" -xzf - govc
      if [ -w /usr/local/bin ]; then
        mv "$tmp/govc" /usr/local/bin/govc
      else
        sudo mv "$tmp/govc" /usr/local/bin/govc
      fi
      chmod +x /usr/local/bin/govc
      ;;
    *)
      echo "Error: unsupported OS: $(uname)" >&2
      exit 3
      ;;
  esac
  log "govc installed: $(govc version 2>&1 | head -1)"
else
  log "govc already installed: $(govc version 2>&1 | head -1)"
fi

# ---------- 2. Write config ----------
# Values are shell-escaped with printf %q so that sourcing the file is safe
# even if HOST/USERNAME/DATACENTER contain single quotes, $ signs, or ;.
CONF_DIR="$HOME/.config/esxi-skill"
CONF_FILE="$CONF_DIR/$PROFILE.env"
mkdir -p "$CONF_DIR"
chmod 700 "$CONF_DIR"

SERVICE="govc-$HOST"
{
  printf '# esxi-skill profile: %s\n' "$PROFILE"
  printf '# Generated by setup.sh — edit at your own risk.\n'
  printf 'export GOVC_URL=%q\n' "$HOST"
  printf 'export GOVC_USERNAME=%q\n' "$USERNAME"
  printf 'export GOVC_INSECURE=%q\n' "$INSECURE"
  printf 'export GOVC_DATACENTER=%q\n' "$DATACENTER"
  printf 'export ESXI_CRED_SERVICE=%q\n' "$SERVICE"
} > "$CONF_FILE"
chmod 600 "$CONF_FILE"
log "Config written: $CONF_FILE"

# ---------- 3. Store password in platform-appropriate keychain ----------
case "$(uname)" in
  Darwin)
    security add-generic-password \
      -a "$USERNAME" \
      -s "$SERVICE" \
      -w "$PASSWORD" \
      -U \
      >/dev/null 2>&1
    log "Password saved to macOS Keychain (account=$USERNAME service=$SERVICE)"
    ;;
  Linux)
    if command -v secret-tool >/dev/null 2>&1; then
      printf '%s' "$PASSWORD" | secret-tool store \
        --label="govc: $USERNAME @ $HOST" \
        service "$SERVICE" \
        account "$USERNAME"
      log "Password saved to libsecret (service=$SERVICE account=$USERNAME)"
    else
      # No libsecret — use chmod-600 file matching g wrapper's fallback lookup
      CRED_FILE="$CONF_DIR/$PROFILE.cred"
      umask 077
      printf '%s' "$PASSWORD" > "$CRED_FILE"
      chmod 600 "$CRED_FILE"
      log "WARNING: libsecret not found; password stored at $CRED_FILE (chmod 600)."
      log "         Install libsecret-tools (apt/dnf) for keyring-backed storage."
    fi
    ;;
  *)
    log "ERROR: unsupported OS: $(uname)"
    exit 5
    ;;
esac

# ---------- 4. Test connection ----------
log "Testing connection..."
if [ "$(uname)" = "Darwin" ]; then
  PW=$(security find-generic-password -a "$USERNAME" -s "$SERVICE" -w)
else
  PW="$PASSWORD"
fi

export GOVC_URL GOVC_USERNAME GOVC_INSECURE GOVC_DATACENTER
GOVC_URL="$HOST" GOVC_USERNAME="$USERNAME" GOVC_INSECURE="$INSECURE" \
  GOVC_DATACENTER="$DATACENTER" GOVC_PASSWORD="$PW" \
  govc about 2>&1 | sed 's/^/[govc] /' || {
    log "Connection test FAILED. Check host/user/password."
    exit 4
  }

log "Setup complete. Profile: $PROFILE, host: $HOST"
log "Use the wrapper: $(dirname "$0")/g <govc-args...>"
